"""Update the V1 capstone brief so it accurately describes SRG Tracker V2.2.

The script deliberately updates only the student's editable responses.  It keeps
the mentor template, headings, and review table intact.
"""

from pathlib import Path

from docx import Document


ROOT = Path(__file__).resolve().parents[1]
BRIEF = ROOT / "docx" / "Capstone_Project.docx"


def set_cell_text(cell, text: str) -> None:
    """Replace a table-cell response while retaining its first paragraph style."""
    paragraph = cell.paragraphs[0]
    if paragraph.runs:
        paragraph.runs[0].text = text
        for run in paragraph.runs[1:]:
            run.text = ""
    else:
        paragraph.add_run(text)
    for extra in cell.paragraphs[1:]:
        extra._element.getparent().remove(extra._element)


def main() -> None:
    doc = Document(BRIEF)

    project = doc.tables[1]
    set_cell_text(project.cell(1, 1), "SRG Tracker - Student Ranking & GPA Tracker")
    set_cell_text(project.cell(3, 1), "Students, instructors, and academic-support teams using an LMS")
    set_cell_text(
        project.cell(4, 1),
        "A history-aware, advisory ML prototype that estimates final GPA, repeat-required course risk, "
        "and learning pace from weekly course history. Individual student ranking is out of scope.",
    )

    set_cell_text(
        doc.tables[2].cell(0, 0),
        "Students and instructors need an early, understandable signal when course progress may require "
        "support. Calculating likely GPA and interpreting weekly effort can be difficult before a course ends. "
        "The intended users are students, instructors, and academic-support teams; predictions are advisory "
        "and must be reviewed by people.",
    )
    set_cell_text(
        doc.tables[3].cell(0, 0),
        "There is no reproducible, privacy-preserving early-warning experiment that converts a student's "
        "complete weekly course history into GPA, outcome-risk, and learning-pace signals. The project uses "
        "synthetic data because real LMS data was not available. Feature ideas were inspired by OULAD and the "
        "exploratory correlation figures in reports/figures/corr-matrix-oulad(1) and (2); no OULAD learner "
        "records are included.",
    )
    set_cell_text(
        doc.tables[4].cell(0, 0),
        "Build a reproducible notebook-based beta product. It accepts the complete ordered weekly history "
        "available through a submitted cutoff, validates the records, and returns advisory estimates of final "
        "GPA, pass/enroll (repeat-required) outcome risk, and learning pace. It must not rank students, grade "
        "them, or make automatic academic decisions.",
    )
    set_cell_text(
        doc.tables[5].cell(0, 0),
        "On the final held-out synthetic test set, the selected GPA model achieved RMSE 0.6661 and R2 0.7749; "
        "the selected course-outcome model achieved enroll F1 0.8305 and enroll recall 0.8474; the selected "
        "learning-pace model achieved macro-F1 0.7799. These are synthetic-data results, not evidence of "
        "performance at a real institution.",
    )

    data_table = doc.tables[6]
    set_cell_text(
        data_table.cell(1, 1),
        "A deterministic synthetic educational dataset generated by Python with seed 20260730. Feature concepts "
        "are inspired by OULAD, but no OULAD records or real student data are included.",
    )
    set_cell_text(data_table.cell(2, 1), "One weekly record for each student-course attempt, ordered from week 1 to week 14.")
    set_cell_text(
        data_table.cell(3, 1),
        "Three targets: final_gpa (0.00-4.50), course_outcome (pass or enroll/repeat-required), and "
        "learning_pace (behind, on_track, ahead).",
    )
    set_cell_text(
        data_table.cell(4, 1),
        "Only history available at prediction time: week number, attendance, LMS activity, assignment and quiz "
        "scores, submission behaviour, corrections, and midterm information after week 7. The full ordered "
        "history through the cutoff is required.",
    )
    set_cell_text(
        data_table.cell(5, 1),
        "The dataset is synthetic and may not represent real student behaviour or a real curriculum. Generation "
        "rules, distributions, and quality checks are documented for auditability.",
    )
    set_cell_text(
        data_table.cell(6, 1),
        "Future outcomes, final GPA, final course outcome, and final_exam_score_audit_only are never model inputs. "
        "Students are disjoint across train, validation, and final-test splits.",
    )
    set_cell_text(
        data_table.cell(7, 1),
        "The dataset contains no real personal data. Predictions are advisory only and must not be used for "
        "ranking, grading, enrolment, discipline, or automated intervention. Any real-data use needs consent, "
        "privacy review, fairness assessment, and human oversight.",
    )

    technical = doc.tables[7]
    set_cell_text(
        technical.cell(1, 1),
        "Three supervised tasks: regression for final_gpa (0.00-4.50), binary classification for course_outcome "
        "(pass or enroll/repeat-required), and multiclass classification for learning_pace (behind, on_track, ahead).",
    )
    set_cell_text(
        technical.cell(2, 1),
        "Frozen V1 latest-snapshot model as a reference; Dummy, linear, HistGradientBoosting, XGBoost, CatBoost, "
        "MLP, and masked raw-sequence GRU baselines where applicable.",
    )
    set_cell_text(
        technical.cell(3, 1),
        "Validation comparison of aggregate-history and raw-sequence approaches. Selected models: CatBoost for "
        "final GPA, shared GRU outcome head for course outcome, and XGBoost for learning pace.",
    )
    set_cell_text(
        technical.cell(4, 1),
        "Student-disjoint split: 300 train, 100 validation, and 50 held-out test students; 3,000, 1,000, and "
        "500 course attempts respectively. Every attempt contains fourteen weekly records. Test data remains "
        "untouched until selection is frozen.",
    )
    set_cell_text(
        technical.cell(5, 1),
        "Selection metrics: GPA RMSE, enroll F1 for course outcome, and macro-F1 for learning pace. Final reporting "
        "also includes GPA MAE/R2, outcome recall/ROC-AUC, and pace balanced accuracy. Rankings store training time, "
        "median inference time, serialized model size, and neural parameter count.",
    )
    set_cell_text(
        technical.cell(6, 1),
        "Complete ordered weekly history through the latest known cutoff, with validated fields. The pipeline builds "
        "aggregate-history features and a masked raw sequence; it rejects future outcomes and unavailable final-exam data.",
    )
    set_cell_text(
        technical.cell(7, 1),
        "Predicted final GPA, pass/enroll risk with probability, and learning pace. Outputs are advisory signals for "
        "human review, not rankings or decisions.",
    )
    set_cell_text(
        technical.cell(8, 1),
        "Synthetic results may not transfer to real learners. Leakage prevention, input validation, student-disjoint "
        "splits, documentation, privacy review, fairness assessment, uncertainty communication, and human oversight "
        "are required before any real-data use.",
    )

    set_cell_text(
        doc.tables[8].cell(0, 0),
        "1. Accept and validate a complete ordered weekly student-course history through a cutoff.\n"
        "2. Predict final GPA from 0.00 to 4.50 without final-course outcomes.\n"
        "3. Classify course outcome as pass or enroll (repeat-required).\n"
        "4. Classify learning pace as behind, on_track, or ahead.\n"
        "5. Return clear advisory results, probability where available, and safe validation errors.\n"
        "6. Prevent future-data leakage and state that individual ranking is out of scope.",
    )
    set_cell_text(
        doc.tables[9].cell(0, 0),
        "- A reproducible generator creates student-disjoint train, validation, and test data.\n"
        "- The pipeline validates complete weekly histories and returns all three advisory predictions.\n"
        "- Multiple aggregate and sequence approaches, including GRU, are compared with baselines.\n"
        "- Validation rankings preserve metrics, model size, training time, and inference time.\n"
        "- Final test metrics are reported only after model selection is frozen.\n"
        "- Colab-compatible notebooks and a widget-based beta demo can be run from repository instructions.",
    )

    scope = doc.tables[10]
    set_cell_text(scope.cell(1, 0), "Advisory GPA, course-outcome, and learning-pace predictions from one student's complete weekly course history.")
    set_cell_text(scope.cell(1, 1), "Individual student ranking, grading, admissions, enrolment, discipline, or any automated academic decision.")
    set_cell_text(scope.cell(2, 0), "Synthetic-data generation, EDA, leakage checks, model comparison, final evaluation, saved models, and notebook demos.")
    set_cell_text(scope.cell(2, 1), "Real LMS data collection, production deployment, authentication, persistent accounts, or an application/API.")
    set_cell_text(scope.cell(3, 0), "Input validation, documented limitations, human-review guidance, and an ipywidgets beta product.")
    set_cell_text(scope.cell(3, 1), "Causal claims, real-world fairness claims, personalised prescriptions, and the React frontend planned for V3.0.")

    set_cell_text(
        doc.tables[11].cell(0, 0),
        "1. Which weekly LMS fields are reliably available before each prediction cutoff?\n"
        "2. How should GPA, pace, and at-risk thresholds be calibrated with approved real historical data?\n"
        "3. What consent, access-control, retention, and human-review process is required before any real-data pilot?\n"
        "4. Which subgroup and calibration checks are needed before educators see outcome-risk probabilities?",
    )

    for paragraph in doc.paragraphs:
        if "Streamlit interface" in paragraph.text or "time-series model" in paragraph.text:
            if paragraph.runs:
                paragraph.runs[0].text = (
                    "Optional V3.0 direction: build a React-based interactive interface after the notebook beta is "
                    "validated; then assess real-data calibration, privacy, and fairness with institutional approval."
                )
                for run in paragraph.runs[1:]:
                    run.text = ""
            break

    doc.save(BRIEF)
    print(f"Updated {BRIEF}")


if __name__ == "__main__":
    main()
