"""Apply approved, local content updates to the existing capstone project brief."""

from pathlib import Path

from docx import Document


ROOT = Path(__file__).resolve().parents[1]
BRIEF = ROOT / "docx" / "Capstone_Project.docx"


def replace_paragraph_text(paragraph, text: str) -> None:
    if paragraph.runs:
        paragraph.runs[0].text = text
        for run in paragraph.runs[1:]:
            run.text = ""
    else:
        paragraph.add_run(text)


def main() -> None:
    doc = Document(BRIEF)

    data_table = doc.tables[6]
    data_table.cell(1, 1).text = (
        "Synthetic educational dataset generated by a deterministic Python script. "
        "Feature concepts are inspired by OULAD; no OULAD records or real student data are included."
    )
    data_table.cell(4, 1).text = (
        "Weekly student-course data available at prediction time: attendance rate, current average grades, assignment and quiz averages, "
        "submission delays, correction count, semester, week, and the midterm score after week 7."
    )
    data_table.cell(5, 1).text = (
        "The dataset is synthetic and may not represent real student behaviour, especially during early weeks. "
        "Its generation rules and expected distributions are documented for auditability."
    )
    data_table.cell(6, 1).text = (
        "The final exam score, final course score, and course outcome are targets only and are never model inputs. "
        "Students are disjoint across train, validation, and test splits."
    )
    data_table.cell(7, 1).text = (
        "The data is synthetic and contains no personal or demographic data. It must not be used for real academic decisions. "
        "The repository documents the generation rules, assumptions, and limitations."
    )

    technical = doc.tables[7]
    technical.cell(1, 1).text = (
        "Three supervised tasks using weekly course snapshots: regression for final_course_score (0-100), "
        "binary classification for course_outcome (pass or enroll/repeat), and multiclass classification for "
        "learning_pace (behind, on_track, ahead)."
    )
    technical.cell(2, 1).text = (
        "DummyRegressor and Ridge Regression for final_course_score; DummyClassifier and Logistic Regression "
        "for course_outcome and learning_pace."
    )
    technical.cell(3, 1).text = (
        "Final score: Ridge Regression, Random Forest Regressor, Gradient Boosting Regressor. "
        "Course outcome: Logistic Regression, Random Forest Classifier, Gradient Boosting Classifier. "
        "Learning pace: Logistic Regression, Random Forest Classifier, Gradient Boosting Classifier."
    )
    technical.cell(4, 1).text = (
        "Student-disjoint split: 300 students for training, 100 for validation, and 50 for held-out test. "
        "Every student has two semesters, five courses, and fourteen weekly snapshots. The test split remains untouched until final evaluation."
    )
    technical.cell(5, 1).text = (
        "Final course score: MAE, RMSE, and R2 because it is a continuous 0-100 target. "
        "Course outcome: recall for detecting students at risk of repeat enrollment, F1 for precision-recall balance, "
        "and ROC-AUC when probabilities are available. Learning pace: macro F1 and balanced accuracy because three classes may be imbalanced. "
        "Cross-validation is used during training only; it is not an evaluation metric."
    )
    technical.cell(6, 1).text = (
        "A student/course weekly snapshot: course ID, semester, week, attendance rate, current average grades, "
        "assignment and quiz averages, submission delays, corrections, and midterm score after it becomes available."
    )
    technical.cell(7, 1).text = (
        "Predicted final course score, pass/enroll risk, and learning pace. The first version does not recommend friends; "
        "it can display a general study-support message based on the prediction."
    )
    technical.cell(8, 1).text = (
        "Synthetic data may not represent real student behaviour, especially in early weeks. Predictions are advisory only. "
        "Final-exam data is excluded from features to prevent leakage, and any real deployment would require privacy review and human oversight."
    )

    functional = doc.tables[8]
    functional.cell(0, 0).text = (
        "1. Accept a weekly student-course snapshot with validated numeric ranges and required fields.\n"
        "2. Predict a final course score from 0 to 100 before the final exam.\n"
        "3. Classify the course outcome as pass or enroll (repeat the course), using the 65-point threshold.\n"
        "4. Classify learning pace as behind, on_track, or ahead.\n"
        "5. Return an understandable advisory message and handle missing or invalid inputs safely."
    )

    acceptance = doc.tables[9]
    acceptance.cell(0, 0).text = (
        "- A reproducible generator creates train, validation, and test CSV files with student-disjoint splits.\n"
        "- The final pipeline accepts raw weekly input and returns all three predictions.\n"
        "- At least two meaningful approaches are compared for each task against a baseline.\n"
        "- Final metrics are reported once on the held-out test set, with error analysis by semester week.\n"
        "- A clean Colab-compatible demo runs from the repository instructions."
    )

    scope = doc.tables[10]
    scope.cell(1, 0).text = "Weekly prediction of final course score, pass/enroll outcome, and learning pace for one student-course record."
    scope.cell(1, 1).text = "Use for real grading, enrolment decisions, disciplinary action, or automated student ranking."
    scope.cell(2, 0).text = "Synthetic-data generation, EDA, preprocessing, model comparison, evaluation, and a reproducible notebook demo."
    scope.cell(2, 1).text = "Collection of real LMS data, deployment to a production LMS, authentication, and persistent user accounts."
    scope.cell(3, 0).text = "Input validation, saved model artifacts, documented limitations, and human-review guidance."
    scope.cell(3, 1).text = "Friend matching, personalised content recommendation, causal claims, and demographic fairness claims."

    questions = doc.tables[11]
    questions.cell(0, 0).text = (
        "1. Which weekly features remain reliably available from an LMS before each prediction date?\n"
        "2. How should learning_pace thresholds be calibrated if real historical data becomes available?\n"
        "3. Does the 65-point pass threshold apply consistently to every course in the intended institution?\n"
        "4. What human-review workflow is required before a student receives an at-risk warning?"
    )

    for paragraph in doc.paragraphs:
        if paragraph.text.strip().startswith("• __________________________________"):
            replace_paragraph_text(
                paragraph,
                "• Add a transparent study-material recommendation module.\n"
                "• Evaluate a time-series model when real longitudinal data becomes available.\n"
                "• Build an approved LMS or Streamlit interface after the notebook demo is complete.",
            )
            break

    doc.save(BRIEF)
    print(f"Updated {BRIEF}")


if __name__ == "__main__":
    main()
